# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='User',
        ),
    ]
